name: Release

on:
  workflow_dispatch:
    inputs:
      electrumx-version:
        description: "ElectrumX Version, eg: v1.2.1"
        required: true
      image-version:
        description: "The version of the image to build"
jobs:
  build:
    permissions:
      contents: read
      id-token: write
    uses: ./.github/workflows/build-image.yml
    with:
      # if image-version is not provided, it will default to electrumx-version
      image-version: ${{ inputs.image-version || inputs.electrumx-version }}
      electrumx-version: ${{ inputs.electrumx-version }}
    secrets: inherit
